'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
'
Namespace com.sunwaysms.sms
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SMSSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ResultBase))>  _
    Partial Public Class SMS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendArrayOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendItemOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendArrayScheduleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMessageIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMessageStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendNumberGroupOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendNumberGroupScheduleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetNumberGroupDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InsertNumberInNumberGroupOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInboxMessageOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInboxMessageWithNumberOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCreditOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetUserInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInboxMessageWithInboxIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SmsProvider.My.MySettings.Default.SmsProvider_com_sunwaysms_sms_SMS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendArrayCompleted As SendArrayCompletedEventHandler
        
        '''<remarks/>
        Public Event SendItemCompleted As SendItemCompletedEventHandler
        
        '''<remarks/>
        Public Event SendArrayScheduleCompleted As SendArrayScheduleCompletedEventHandler
        
        '''<remarks/>
        Public Event GetMessageIDCompleted As GetMessageIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GetMessageStatusCompleted As GetMessageStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event SendNumberGroupCompleted As SendNumberGroupCompletedEventHandler
        
        '''<remarks/>
        Public Event SendNumberGroupScheduleCompleted As SendNumberGroupScheduleCompletedEventHandler
        
        '''<remarks/>
        Public Event GetNumberGroupDataCompleted As GetNumberGroupDataCompletedEventHandler
        
        '''<remarks/>
        Public Event InsertNumberInNumberGroupCompleted As InsertNumberInNumberGroupCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInboxMessageCompleted As GetInboxMessageCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInboxMessageWithNumberCompleted As GetInboxMessageWithNumberCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCreditCompleted As GetCreditCompletedEventHandler
        
        '''<remarks/>
        Public Event GetUserInfoCompleted As GetUserInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInboxMessageWithInboxIDCompleted As GetInboxMessageWithInboxIDCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendArray", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendArray(ByVal UserName As String, ByVal Password As String, ByVal RecipientNumber() As String, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal CheckingMessageID() As Long) As Long()
            Dim results() As Object = Me.Invoke("SendArray", New Object() {UserName, Password, RecipientNumber, MessageBody, SpecialNumber, IsFlashMessage, CheckingMessageID})
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendArrayAsync(ByVal UserName As String, ByVal Password As String, ByVal RecipientNumber() As String, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal CheckingMessageID() As Long)
            Me.SendArrayAsync(UserName, Password, RecipientNumber, MessageBody, SpecialNumber, IsFlashMessage, CheckingMessageID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendArrayAsync(ByVal UserName As String, ByVal Password As String, ByVal RecipientNumber() As String, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal CheckingMessageID() As Long, ByVal userState As Object)
            If (Me.SendArrayOperationCompleted Is Nothing) Then
                Me.SendArrayOperationCompleted = AddressOf Me.OnSendArrayOperationCompleted
            End If
            Me.InvokeAsync("SendArray", New Object() {UserName, Password, RecipientNumber, MessageBody, SpecialNumber, IsFlashMessage, CheckingMessageID}, Me.SendArrayOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendArrayOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendArrayCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendArrayCompleted(Me, New SendArrayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendItem", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendItem(ByVal UserName As String, ByVal Password As String, ByVal RecipientNumber As String, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal CheckingMessageID As Long) As Long
            Dim results() As Object = Me.Invoke("SendItem", New Object() {UserName, Password, RecipientNumber, MessageBody, SpecialNumber, IsFlashMessage, CheckingMessageID})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendItemAsync(ByVal UserName As String, ByVal Password As String, ByVal RecipientNumber As String, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal CheckingMessageID As Long)
            Me.SendItemAsync(UserName, Password, RecipientNumber, MessageBody, SpecialNumber, IsFlashMessage, CheckingMessageID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendItemAsync(ByVal UserName As String, ByVal Password As String, ByVal RecipientNumber As String, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal CheckingMessageID As Long, ByVal userState As Object)
            If (Me.SendItemOperationCompleted Is Nothing) Then
                Me.SendItemOperationCompleted = AddressOf Me.OnSendItemOperationCompleted
            End If
            Me.InvokeAsync("SendItem", New Object() {UserName, Password, RecipientNumber, MessageBody, SpecialNumber, IsFlashMessage, CheckingMessageID}, Me.SendItemOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendItemOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendItemCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendItemCompleted(Me, New SendItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendArraySchedule", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendArraySchedule(ByVal UserName As String, ByVal Password As String, ByVal RecipientNumber() As String, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal Year As Integer, ByVal Month As Integer, ByVal Day As Integer, ByVal Hour As Integer, ByVal Minute As Integer) As Long
            Dim results() As Object = Me.Invoke("SendArraySchedule", New Object() {UserName, Password, RecipientNumber, MessageBody, SpecialNumber, IsFlashMessage, Year, Month, Day, Hour, Minute})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendArrayScheduleAsync(ByVal UserName As String, ByVal Password As String, ByVal RecipientNumber() As String, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal Year As Integer, ByVal Month As Integer, ByVal Day As Integer, ByVal Hour As Integer, ByVal Minute As Integer)
            Me.SendArrayScheduleAsync(UserName, Password, RecipientNumber, MessageBody, SpecialNumber, IsFlashMessage, Year, Month, Day, Hour, Minute, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendArrayScheduleAsync(ByVal UserName As String, ByVal Password As String, ByVal RecipientNumber() As String, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal Year As Integer, ByVal Month As Integer, ByVal Day As Integer, ByVal Hour As Integer, ByVal Minute As Integer, ByVal userState As Object)
            If (Me.SendArrayScheduleOperationCompleted Is Nothing) Then
                Me.SendArrayScheduleOperationCompleted = AddressOf Me.OnSendArrayScheduleOperationCompleted
            End If
            Me.InvokeAsync("SendArraySchedule", New Object() {UserName, Password, RecipientNumber, MessageBody, SpecialNumber, IsFlashMessage, Year, Month, Day, Hour, Minute}, Me.SendArrayScheduleOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendArrayScheduleOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendArrayScheduleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendArrayScheduleCompleted(Me, New SendArrayScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMessageID(ByVal UserName As String, ByVal Password As String, ByVal CheckingMessageID() As Long) As Long()
            Dim results() As Object = Me.Invoke("GetMessageID", New Object() {UserName, Password, CheckingMessageID})
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMessageIDAsync(ByVal UserName As String, ByVal Password As String, ByVal CheckingMessageID() As Long)
            Me.GetMessageIDAsync(UserName, Password, CheckingMessageID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMessageIDAsync(ByVal UserName As String, ByVal Password As String, ByVal CheckingMessageID() As Long, ByVal userState As Object)
            If (Me.GetMessageIDOperationCompleted Is Nothing) Then
                Me.GetMessageIDOperationCompleted = AddressOf Me.OnGetMessageIDOperationCompleted
            End If
            Me.InvokeAsync("GetMessageID", New Object() {UserName, Password, CheckingMessageID}, Me.GetMessageIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMessageIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMessageIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMessageIDCompleted(Me, New GetMessageIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetMessageStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMessageStatus(ByVal UserName As String, ByVal Password As String, ByVal MessageID() As Long) As Long()
            Dim results() As Object = Me.Invoke("GetMessageStatus", New Object() {UserName, Password, MessageID})
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMessageStatusAsync(ByVal UserName As String, ByVal Password As String, ByVal MessageID() As Long)
            Me.GetMessageStatusAsync(UserName, Password, MessageID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMessageStatusAsync(ByVal UserName As String, ByVal Password As String, ByVal MessageID() As Long, ByVal userState As Object)
            If (Me.GetMessageStatusOperationCompleted Is Nothing) Then
                Me.GetMessageStatusOperationCompleted = AddressOf Me.OnGetMessageStatusOperationCompleted
            End If
            Me.InvokeAsync("GetMessageStatus", New Object() {UserName, Password, MessageID}, Me.GetMessageStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMessageStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMessageStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMessageStatusCompleted(Me, New GetMessageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendNumberGroup", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendNumberGroup(ByVal UserName As String, ByVal Password As String, ByVal NumberGroupID() As Long, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal DontSendToRepeatedNumber As Boolean) As Long
            Dim results() As Object = Me.Invoke("SendNumberGroup", New Object() {UserName, Password, NumberGroupID, MessageBody, SpecialNumber, IsFlashMessage, DontSendToRepeatedNumber})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendNumberGroupAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberGroupID() As Long, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal DontSendToRepeatedNumber As Boolean)
            Me.SendNumberGroupAsync(UserName, Password, NumberGroupID, MessageBody, SpecialNumber, IsFlashMessage, DontSendToRepeatedNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendNumberGroupAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberGroupID() As Long, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal DontSendToRepeatedNumber As Boolean, ByVal userState As Object)
            If (Me.SendNumberGroupOperationCompleted Is Nothing) Then
                Me.SendNumberGroupOperationCompleted = AddressOf Me.OnSendNumberGroupOperationCompleted
            End If
            Me.InvokeAsync("SendNumberGroup", New Object() {UserName, Password, NumberGroupID, MessageBody, SpecialNumber, IsFlashMessage, DontSendToRepeatedNumber}, Me.SendNumberGroupOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendNumberGroupOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendNumberGroupCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendNumberGroupCompleted(Me, New SendNumberGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendNumberGroupSchedule", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SendNumberGroupSchedule(ByVal UserName As String, ByVal Password As String, ByVal NumberGroupID() As Long, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal DontSendToRepeatedNumber As Boolean, ByVal Year As Integer, ByVal Month As Integer, ByVal Day As Integer, ByVal Hour As Integer, ByVal Minute As Integer) As Long
            Dim results() As Object = Me.Invoke("SendNumberGroupSchedule", New Object() {UserName, Password, NumberGroupID, MessageBody, SpecialNumber, IsFlashMessage, DontSendToRepeatedNumber, Year, Month, Day, Hour, Minute})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendNumberGroupScheduleAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberGroupID() As Long, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal DontSendToRepeatedNumber As Boolean, ByVal Year As Integer, ByVal Month As Integer, ByVal Day As Integer, ByVal Hour As Integer, ByVal Minute As Integer)
            Me.SendNumberGroupScheduleAsync(UserName, Password, NumberGroupID, MessageBody, SpecialNumber, IsFlashMessage, DontSendToRepeatedNumber, Year, Month, Day, Hour, Minute, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendNumberGroupScheduleAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberGroupID() As Long, ByVal MessageBody As String, ByVal SpecialNumber As String, ByVal IsFlashMessage As Boolean, ByVal DontSendToRepeatedNumber As Boolean, ByVal Year As Integer, ByVal Month As Integer, ByVal Day As Integer, ByVal Hour As Integer, ByVal Minute As Integer, ByVal userState As Object)
            If (Me.SendNumberGroupScheduleOperationCompleted Is Nothing) Then
                Me.SendNumberGroupScheduleOperationCompleted = AddressOf Me.OnSendNumberGroupScheduleOperationCompleted
            End If
            Me.InvokeAsync("SendNumberGroupSchedule", New Object() {UserName, Password, NumberGroupID, MessageBody, SpecialNumber, IsFlashMessage, DontSendToRepeatedNumber, Year, Month, Day, Hour, Minute}, Me.SendNumberGroupScheduleOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendNumberGroupScheduleOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendNumberGroupScheduleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendNumberGroupScheduleCompleted(Me, New SendNumberGroupScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNumberGroupData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetNumberGroupData(ByVal UserName As String, ByVal Password As String) As NumberGroupItem()
            Dim results() As Object = Me.Invoke("GetNumberGroupData", New Object() {UserName, Password})
            Return CType(results(0),NumberGroupItem())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetNumberGroupDataAsync(ByVal UserName As String, ByVal Password As String)
            Me.GetNumberGroupDataAsync(UserName, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetNumberGroupDataAsync(ByVal UserName As String, ByVal Password As String, ByVal userState As Object)
            If (Me.GetNumberGroupDataOperationCompleted Is Nothing) Then
                Me.GetNumberGroupDataOperationCompleted = AddressOf Me.OnGetNumberGroupDataOperationCompleted
            End If
            Me.InvokeAsync("GetNumberGroupData", New Object() {UserName, Password}, Me.GetNumberGroupDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetNumberGroupDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetNumberGroupDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetNumberGroupDataCompleted(Me, New GetNumberGroupDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertNumberInNumberGroup", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InsertNumberInNumberGroup(ByVal UserName As String, ByVal Password As String, ByVal NumberGroupID As Long, ByVal PersonNumber() As String, ByVal PersonName() As String) As Long()
            Dim results() As Object = Me.Invoke("InsertNumberInNumberGroup", New Object() {UserName, Password, NumberGroupID, PersonNumber, PersonName})
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Overloads Sub InsertNumberInNumberGroupAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberGroupID As Long, ByVal PersonNumber() As String, ByVal PersonName() As String)
            Me.InsertNumberInNumberGroupAsync(UserName, Password, NumberGroupID, PersonNumber, PersonName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InsertNumberInNumberGroupAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberGroupID As Long, ByVal PersonNumber() As String, ByVal PersonName() As String, ByVal userState As Object)
            If (Me.InsertNumberInNumberGroupOperationCompleted Is Nothing) Then
                Me.InsertNumberInNumberGroupOperationCompleted = AddressOf Me.OnInsertNumberInNumberGroupOperationCompleted
            End If
            Me.InvokeAsync("InsertNumberInNumberGroup", New Object() {UserName, Password, NumberGroupID, PersonNumber, PersonName}, Me.InsertNumberInNumberGroupOperationCompleted, userState)
        End Sub
        
        Private Sub OnInsertNumberInNumberGroupOperationCompleted(ByVal arg As Object)
            If (Not (Me.InsertNumberInNumberGroupCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InsertNumberInNumberGroupCompleted(Me, New InsertNumberInNumberGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInboxMessage", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInboxMessage(ByVal UserName As String, ByVal Password As String, ByVal NumberOfMessage As Integer) As InboxItem()
            Dim results() As Object = Me.Invoke("GetInboxMessage", New Object() {UserName, Password, NumberOfMessage})
            Return CType(results(0),InboxItem())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInboxMessageAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberOfMessage As Integer)
            Me.GetInboxMessageAsync(UserName, Password, NumberOfMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInboxMessageAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberOfMessage As Integer, ByVal userState As Object)
            If (Me.GetInboxMessageOperationCompleted Is Nothing) Then
                Me.GetInboxMessageOperationCompleted = AddressOf Me.OnGetInboxMessageOperationCompleted
            End If
            Me.InvokeAsync("GetInboxMessage", New Object() {UserName, Password, NumberOfMessage}, Me.GetInboxMessageOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInboxMessageOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInboxMessageCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInboxMessageCompleted(Me, New GetInboxMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInboxMessageWithNumber", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInboxMessageWithNumber(ByVal UserName As String, ByVal Password As String, ByVal NumberOfMessage As Integer, ByVal SpecialNumber As String) As InboxItem()
            Dim results() As Object = Me.Invoke("GetInboxMessageWithNumber", New Object() {UserName, Password, NumberOfMessage, SpecialNumber})
            Return CType(results(0),InboxItem())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInboxMessageWithNumberAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberOfMessage As Integer, ByVal SpecialNumber As String)
            Me.GetInboxMessageWithNumberAsync(UserName, Password, NumberOfMessage, SpecialNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInboxMessageWithNumberAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberOfMessage As Integer, ByVal SpecialNumber As String, ByVal userState As Object)
            If (Me.GetInboxMessageWithNumberOperationCompleted Is Nothing) Then
                Me.GetInboxMessageWithNumberOperationCompleted = AddressOf Me.OnGetInboxMessageWithNumberOperationCompleted
            End If
            Me.InvokeAsync("GetInboxMessageWithNumber", New Object() {UserName, Password, NumberOfMessage, SpecialNumber}, Me.GetInboxMessageWithNumberOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInboxMessageWithNumberOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInboxMessageWithNumberCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInboxMessageWithNumberCompleted(Me, New GetInboxMessageWithNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCredit", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetCredit(ByVal UserName As String, ByVal Password As String) As Long
            Dim results() As Object = Me.Invoke("GetCredit", New Object() {UserName, Password})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCreditAsync(ByVal UserName As String, ByVal Password As String)
            Me.GetCreditAsync(UserName, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCreditAsync(ByVal UserName As String, ByVal Password As String, ByVal userState As Object)
            If (Me.GetCreditOperationCompleted Is Nothing) Then
                Me.GetCreditOperationCompleted = AddressOf Me.OnGetCreditOperationCompleted
            End If
            Me.InvokeAsync("GetCredit", New Object() {UserName, Password}, Me.GetCreditOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCreditOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCreditCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCreditCompleted(Me, New GetCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetUserInfo(ByVal UserName As String, ByVal Password As String) As ProfileInfo
            Dim results() As Object = Me.Invoke("GetUserInfo", New Object() {UserName, Password})
            Return CType(results(0),ProfileInfo)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetUserInfoAsync(ByVal UserName As String, ByVal Password As String)
            Me.GetUserInfoAsync(UserName, Password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetUserInfoAsync(ByVal UserName As String, ByVal Password As String, ByVal userState As Object)
            If (Me.GetUserInfoOperationCompleted Is Nothing) Then
                Me.GetUserInfoOperationCompleted = AddressOf Me.OnGetUserInfoOperationCompleted
            End If
            Me.InvokeAsync("GetUserInfo", New Object() {UserName, Password}, Me.GetUserInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetUserInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetUserInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetUserInfoCompleted(Me, New GetUserInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInboxMessageWithInboxID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetInboxMessageWithInboxID(ByVal UserName As String, ByVal Password As String, ByVal NumberOfMessage As Integer, ByVal InboxID As Integer, ByVal IsReaded As Boolean) As ResultInbox
            Dim results() As Object = Me.Invoke("GetInboxMessageWithInboxID", New Object() {UserName, Password, NumberOfMessage, InboxID, IsReaded})
            Return CType(results(0),ResultInbox)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetInboxMessageWithInboxIDAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberOfMessage As Integer, ByVal InboxID As Integer, ByVal IsReaded As Boolean)
            Me.GetInboxMessageWithInboxIDAsync(UserName, Password, NumberOfMessage, InboxID, IsReaded, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInboxMessageWithInboxIDAsync(ByVal UserName As String, ByVal Password As String, ByVal NumberOfMessage As Integer, ByVal InboxID As Integer, ByVal IsReaded As Boolean, ByVal userState As Object)
            If (Me.GetInboxMessageWithInboxIDOperationCompleted Is Nothing) Then
                Me.GetInboxMessageWithInboxIDOperationCompleted = AddressOf Me.OnGetInboxMessageWithInboxIDOperationCompleted
            End If
            Me.InvokeAsync("GetInboxMessageWithInboxID", New Object() {UserName, Password, NumberOfMessage, InboxID, IsReaded}, Me.GetInboxMessageWithInboxIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInboxMessageWithInboxIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInboxMessageWithInboxIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInboxMessageWithInboxIDCompleted(Me, New GetInboxMessageWithInboxIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class NumberGroupItem
        
        Private numberGroupIDField As Long
        
        Private numberCountField As Integer
        
        Private farsiNameField As String
        
        Private englishNameField As String
        
        Private priorityField As Integer
        
        '''<remarks/>
        Public Property NumberGroupID() As Long
            Get
                Return Me.numberGroupIDField
            End Get
            Set
                Me.numberGroupIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NumberCount() As Integer
            Get
                Return Me.numberCountField
            End Get
            Set
                Me.numberCountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FarsiName() As String
            Get
                Return Me.farsiNameField
            End Get
            Set
                Me.farsiNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EnglishName() As String
            Get
                Return Me.englishNameField
            End Get
            Set
                Me.englishNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Priority() As Integer
            Get
                Return Me.priorityField
            End Get
            Set
                Me.priorityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InboxItem2
        
        Private inboxIDField As Long
        
        Private specialNumberField As String
        
        Private senderNumberField As String
        
        Private messageBodyField As String
        
        Private receiveDateField As Date
        
        Private uDHField As String
        
        '''<remarks/>
        Public Property InboxID() As Long
            Get
                Return Me.inboxIDField
            End Get
            Set
                Me.inboxIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SpecialNumber() As String
            Get
                Return Me.specialNumberField
            End Get
            Set
                Me.specialNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SenderNumber() As String
            Get
                Return Me.senderNumberField
            End Get
            Set
                Me.senderNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MessageBody() As String
            Get
                Return Me.messageBodyField
            End Get
            Set
                Me.messageBodyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiveDate() As Date
            Get
                Return Me.receiveDateField
            End Get
            Set
                Me.receiveDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UDH() As String
            Get
                Return Me.uDHField
            End Get
            Set
                Me.uDHField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ResultInbox)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public MustInherit Class ResultBase
        
        Private statusField As Integer
        
        '''<remarks/>
        Public Property Status() As Integer
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ResultInbox
        Inherits ResultBase
        
        Private messagesField() As InboxItem2
        
        '''<remarks/>
        Public Property Messages() As InboxItem2()
            Get
                Return Me.messagesField
            End Get
            Set
                Me.messagesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ProfileInfo
        
        Private sMSCreditField As Integer
        
        Private totalSendSMSField As Integer
        
        Private totalReciveSMSField As Integer
        
        Private totalIncomeSMSField As Integer
        
        Private notificationsField As String
        
        Private notificationsDiscField As String
        
        Private notificationsDateField As Date
        
        Private publicNotificationsField As String
        
        Private publicNotificationsDiscField As String
        
        Private publicNotificationsDateField As Date
        
        Private statusField As Long
        
        '''<remarks/>
        Public Property SMSCredit() As Integer
            Get
                Return Me.sMSCreditField
            End Get
            Set
                Me.sMSCreditField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalSendSMS() As Integer
            Get
                Return Me.totalSendSMSField
            End Get
            Set
                Me.totalSendSMSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalReciveSMS() As Integer
            Get
                Return Me.totalReciveSMSField
            End Get
            Set
                Me.totalReciveSMSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalIncomeSMS() As Integer
            Get
                Return Me.totalIncomeSMSField
            End Get
            Set
                Me.totalIncomeSMSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Notifications() As String
            Get
                Return Me.notificationsField
            End Get
            Set
                Me.notificationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NotificationsDisc() As String
            Get
                Return Me.notificationsDiscField
            End Get
            Set
                Me.notificationsDiscField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NotificationsDate() As Date
            Get
                Return Me.notificationsDateField
            End Get
            Set
                Me.notificationsDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PublicNotifications() As String
            Get
                Return Me.publicNotificationsField
            End Get
            Set
                Me.publicNotificationsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PublicNotificationsDisc() As String
            Get
                Return Me.publicNotificationsDiscField
            End Get
            Set
                Me.publicNotificationsDiscField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PublicNotificationsDate() As Date
            Get
                Return Me.publicNotificationsDateField
            End Get
            Set
                Me.publicNotificationsDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As Long
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InboxItem
        
        Private inboxIDField As Long
        
        Private specialNumberField As String
        
        Private senderNumberField As String
        
        Private messageBodyField As String
        
        Private receiveDateField As String
        
        Private uDHField As String
        
        '''<remarks/>
        Public Property InboxID() As Long
            Get
                Return Me.inboxIDField
            End Get
            Set
                Me.inboxIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SpecialNumber() As String
            Get
                Return Me.specialNumberField
            End Get
            Set
                Me.specialNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SenderNumber() As String
            Get
                Return Me.senderNumberField
            End Get
            Set
                Me.senderNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MessageBody() As String
            Get
                Return Me.messageBodyField
            End Get
            Set
                Me.messageBodyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ReceiveDate() As String
            Get
                Return Me.receiveDateField
            End Get
            Set
                Me.receiveDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UDH() As String
            Get
                Return Me.uDHField
            End Get
            Set
                Me.uDHField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SendArrayCompletedEventHandler(ByVal sender As Object, ByVal e As SendArrayCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendArrayCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SendItemCompletedEventHandler(ByVal sender As Object, ByVal e As SendItemCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendItemCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SendArrayScheduleCompletedEventHandler(ByVal sender As Object, ByVal e As SendArrayScheduleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendArrayScheduleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetMessageIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetMessageIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMessageIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetMessageStatusCompletedEventHandler(ByVal sender As Object, ByVal e As GetMessageStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMessageStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SendNumberGroupCompletedEventHandler(ByVal sender As Object, ByVal e As SendNumberGroupCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendNumberGroupCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SendNumberGroupScheduleCompletedEventHandler(ByVal sender As Object, ByVal e As SendNumberGroupScheduleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendNumberGroupScheduleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetNumberGroupDataCompletedEventHandler(ByVal sender As Object, ByVal e As GetNumberGroupDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetNumberGroupDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As NumberGroupItem()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),NumberGroupItem())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub InsertNumberInNumberGroupCompletedEventHandler(ByVal sender As Object, ByVal e As InsertNumberInNumberGroupCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InsertNumberInNumberGroupCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetInboxMessageCompletedEventHandler(ByVal sender As Object, ByVal e As GetInboxMessageCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInboxMessageCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As InboxItem()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),InboxItem())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetInboxMessageWithNumberCompletedEventHandler(ByVal sender As Object, ByVal e As GetInboxMessageWithNumberCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInboxMessageWithNumberCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As InboxItem()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),InboxItem())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetCreditCompletedEventHandler(ByVal sender As Object, ByVal e As GetCreditCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCreditCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetUserInfoCompletedEventHandler(ByVal sender As Object, ByVal e As GetUserInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetUserInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ProfileInfo
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ProfileInfo)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetInboxMessageWithInboxIDCompletedEventHandler(ByVal sender As Object, ByVal e As GetInboxMessageWithInboxIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInboxMessageWithInboxIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ResultInbox
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ResultInbox)
            End Get
        End Property
    End Class
End Namespace
