'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
'
Namespace com.adpdigital.ws2
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="MessagingServiceSoapBinding", [Namespace]:="http://www.adpdigital.com/services/messaging"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(MessageObject)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Result))>  _
    Partial Public Class JaxRpcMessagingServiceService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private sendMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getBalanceOperationCompleted As System.Threading.SendOrPostCallback
        
        Private changePasswordOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private receiveOperationCompleted As System.Threading.SendOrPostCallback
        
        Private sendOperationCompleted As System.Threading.SendOrPostCallback
        
        Private reportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private statusReportOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SmsProvider.My.MySettings.Default.SmsProvider_com_adpdigital_ws2_JaxRpcMessagingServiceService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event sendMultipleCompleted As sendMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event getBalanceCompleted As getBalanceCompletedEventHandler
        
        '''<remarks/>
        Public Event changePasswordCompleted As changePasswordCompletedEventHandler
        
        '''<remarks/>
        Public Event getStatusCompleted As getStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event receiveCompleted As receiveCompletedEventHandler
        
        '''<remarks/>
        Public Event sendCompleted As sendCompletedEventHandler
        
        '''<remarks/>
        Public Event reportCompleted As reportCompletedEventHandler
        
        '''<remarks/>
        Public Event statusReportCompleted As statusReportCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://www.adpdigital.com/services/messaging", ResponseNamespace:="http://www.adpdigital.com/services/messaging", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function sendMultiple(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal sourcePort As String, ByVal destPort As String, ByVal messageType As Short, ByVal longSupported As Boolean, <System.Xml.Serialization.XmlElementAttribute("messages")> ByVal messages() As MultiAddressMessageObject) As <System.Xml.Serialization.XmlElementAttribute("sendMultipleReturn")> SendResult
            Dim results() As Object = Me.Invoke("sendMultiple", New Object() {userName, password, shortNumber, sourcePort, destPort, messageType, longSupported, messages})
            Return CType(results(0),SendResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub sendMultipleAsync(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal sourcePort As String, ByVal destPort As String, ByVal messageType As Short, ByVal longSupported As Boolean, ByVal messages() As MultiAddressMessageObject)
            Me.sendMultipleAsync(userName, password, shortNumber, sourcePort, destPort, messageType, longSupported, messages, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub sendMultipleAsync(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal sourcePort As String, ByVal destPort As String, ByVal messageType As Short, ByVal longSupported As Boolean, ByVal messages() As MultiAddressMessageObject, ByVal userState As Object)
            If (Me.sendMultipleOperationCompleted Is Nothing) Then
                Me.sendMultipleOperationCompleted = AddressOf Me.OnsendMultipleOperationCompleted
            End If
            Me.InvokeAsync("sendMultiple", New Object() {userName, password, shortNumber, sourcePort, destPort, messageType, longSupported, messages}, Me.sendMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnsendMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.sendMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent sendMultipleCompleted(Me, New sendMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://www.adpdigital.com/services/messaging", ResponseNamespace:="http://www.adpdigital.com/services/messaging", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getBalance(ByVal userName As String, ByVal password As String, ByVal facilityId As Short) As <System.Xml.Serialization.XmlElementAttribute("getBalanceReturn")> BalanceResult
            Dim results() As Object = Me.Invoke("getBalance", New Object() {userName, password, facilityId})
            Return CType(results(0),BalanceResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getBalanceAsync(ByVal userName As String, ByVal password As String, ByVal facilityId As Short)
            Me.getBalanceAsync(userName, password, facilityId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getBalanceAsync(ByVal userName As String, ByVal password As String, ByVal facilityId As Short, ByVal userState As Object)
            If (Me.getBalanceOperationCompleted Is Nothing) Then
                Me.getBalanceOperationCompleted = AddressOf Me.OngetBalanceOperationCompleted
            End If
            Me.InvokeAsync("getBalance", New Object() {userName, password, facilityId}, Me.getBalanceOperationCompleted, userState)
        End Sub
        
        Private Sub OngetBalanceOperationCompleted(ByVal arg As Object)
            If (Not (Me.getBalanceCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getBalanceCompleted(Me, New getBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://www.adpdigital.com/services/messaging", ResponseNamespace:="http://www.adpdigital.com/services/messaging", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function changePassword(ByVal userName As String, ByVal currentPassword As String, ByVal newPassword As String) As <System.Xml.Serialization.XmlElementAttribute("changePasswordReturn")> Short
            Dim results() As Object = Me.Invoke("changePassword", New Object() {userName, currentPassword, newPassword})
            Return CType(results(0),Short)
        End Function
        
        '''<remarks/>
        Public Overloads Sub changePasswordAsync(ByVal userName As String, ByVal currentPassword As String, ByVal newPassword As String)
            Me.changePasswordAsync(userName, currentPassword, newPassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub changePasswordAsync(ByVal userName As String, ByVal currentPassword As String, ByVal newPassword As String, ByVal userState As Object)
            If (Me.changePasswordOperationCompleted Is Nothing) Then
                Me.changePasswordOperationCompleted = AddressOf Me.OnchangePasswordOperationCompleted
            End If
            Me.InvokeAsync("changePassword", New Object() {userName, currentPassword, newPassword}, Me.changePasswordOperationCompleted, userState)
        End Sub
        
        Private Sub OnchangePasswordOperationCompleted(ByVal arg As Object)
            If (Not (Me.changePasswordCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent changePasswordCompleted(Me, New changePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://www.adpdigital.com/services/messaging", ResponseNamespace:="http://www.adpdigital.com/services/messaging", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getStatus(ByVal messageId As Long) As <System.Xml.Serialization.XmlElementAttribute("getStatusReturn")> Short
            Dim results() As Object = Me.Invoke("getStatus", New Object() {messageId})
            Return CType(results(0),Short)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getStatusAsync(ByVal messageId As Long)
            Me.getStatusAsync(messageId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getStatusAsync(ByVal messageId As Long, ByVal userState As Object)
            If (Me.getStatusOperationCompleted Is Nothing) Then
                Me.getStatusOperationCompleted = AddressOf Me.OngetStatusOperationCompleted
            End If
            Me.InvokeAsync("getStatus", New Object() {messageId}, Me.getStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OngetStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.getStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getStatusCompleted(Me, New getStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://www.adpdigital.com/services/messaging", ResponseNamespace:="http://www.adpdigital.com/services/messaging", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function receive(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal start As Long, ByVal maxSize As Integer) As <System.Xml.Serialization.XmlElementAttribute("receiveReturn")> ReceiveResult
            Dim results() As Object = Me.Invoke("receive", New Object() {userName, password, shortNumber, start, maxSize})
            Return CType(results(0),ReceiveResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub receiveAsync(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal start As Long, ByVal maxSize As Integer)
            Me.receiveAsync(userName, password, shortNumber, start, maxSize, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub receiveAsync(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal start As Long, ByVal maxSize As Integer, ByVal userState As Object)
            If (Me.receiveOperationCompleted Is Nothing) Then
                Me.receiveOperationCompleted = AddressOf Me.OnreceiveOperationCompleted
            End If
            Me.InvokeAsync("receive", New Object() {userName, password, shortNumber, start, maxSize}, Me.receiveOperationCompleted, userState)
        End Sub
        
        Private Sub OnreceiveOperationCompleted(ByVal arg As Object)
            If (Not (Me.receiveCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent receiveCompleted(Me, New receiveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://www.adpdigital.com/services/messaging", ResponseNamespace:="http://www.adpdigital.com/services/messaging", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function send(ByVal userName As String, ByVal password As String, ByVal sourceNo As String, <System.Xml.Serialization.XmlElementAttribute("destNo")> ByVal destNo() As String, ByVal sourcePort As String, ByVal destPort As String, <System.Xml.Serialization.XmlElementAttribute("clientId")> ByVal clientId() As String, ByVal messageType As Short, ByVal encoding As Short, ByVal longSupported As Boolean, ByVal dueTime As Date, ByVal content As String) As <System.Xml.Serialization.XmlElementAttribute("sendReturn")> SendResult
            Dim results() As Object = Me.Invoke("send", New Object() {userName, password, sourceNo, destNo, sourcePort, destPort, clientId, messageType, encoding, longSupported, dueTime, content})
            Return CType(results(0),SendResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub sendAsync(ByVal userName As String, ByVal password As String, ByVal sourceNo As String, ByVal destNo() As String, ByVal sourcePort As String, ByVal destPort As String, ByVal clientId() As String, ByVal messageType As Short, ByVal encoding As Short, ByVal longSupported As Boolean, ByVal dueTime As Date, ByVal content As String)
            Me.sendAsync(userName, password, sourceNo, destNo, sourcePort, destPort, clientId, messageType, encoding, longSupported, dueTime, content, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub sendAsync(ByVal userName As String, ByVal password As String, ByVal sourceNo As String, ByVal destNo() As String, ByVal sourcePort As String, ByVal destPort As String, ByVal clientId() As String, ByVal messageType As Short, ByVal encoding As Short, ByVal longSupported As Boolean, ByVal dueTime As Date, ByVal content As String, ByVal userState As Object)
            If (Me.sendOperationCompleted Is Nothing) Then
                Me.sendOperationCompleted = AddressOf Me.OnsendOperationCompleted
            End If
            Me.InvokeAsync("send", New Object() {userName, password, sourceNo, destNo, sourcePort, destPort, clientId, messageType, encoding, longSupported, dueTime, content}, Me.sendOperationCompleted, userState)
        End Sub
        
        Private Sub OnsendOperationCompleted(ByVal arg As Object)
            If (Not (Me.sendCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent sendCompleted(Me, New sendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://www.adpdigital.com/services/messaging", ResponseNamespace:="http://www.adpdigital.com/services/messaging", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function report(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal fromClientId As String, ByVal clientId As String, ByVal fromId As String, ByVal id As String, ByVal maxSize As Integer) As <System.Xml.Serialization.XmlElementAttribute("reportReturn")> ReportResult
            Dim results() As Object = Me.Invoke("report", New Object() {userName, password, shortNumber, fromClientId, clientId, fromId, id, maxSize})
            Return CType(results(0),ReportResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub reportAsync(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal fromClientId As String, ByVal clientId As String, ByVal fromId As String, ByVal id As String, ByVal maxSize As Integer)
            Me.reportAsync(userName, password, shortNumber, fromClientId, clientId, fromId, id, maxSize, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub reportAsync(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal fromClientId As String, ByVal clientId As String, ByVal fromId As String, ByVal id As String, ByVal maxSize As Integer, ByVal userState As Object)
            If (Me.reportOperationCompleted Is Nothing) Then
                Me.reportOperationCompleted = AddressOf Me.OnreportOperationCompleted
            End If
            Me.InvokeAsync("report", New Object() {userName, password, shortNumber, fromClientId, clientId, fromId, id, maxSize}, Me.reportOperationCompleted, userState)
        End Sub
        
        Private Sub OnreportOperationCompleted(ByVal arg As Object)
            If (Not (Me.reportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent reportCompleted(Me, New reportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://www.adpdigital.com/services/messaging", ResponseNamespace:="http://www.adpdigital.com/services/messaging", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function statusReport(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal type As String, <System.Xml.Serialization.XmlElementAttribute("ids")> ByVal ids() As Long, <System.Xml.Serialization.XmlElementAttribute("clientIds")> ByVal clientIds() As String) As <System.Xml.Serialization.XmlElementAttribute("statusReportReturn")> StatusReportResult
            Dim results() As Object = Me.Invoke("statusReport", New Object() {userName, password, shortNumber, type, ids, clientIds})
            Return CType(results(0),StatusReportResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub statusReportAsync(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal type As String, ByVal ids() As Long, ByVal clientIds() As String)
            Me.statusReportAsync(userName, password, shortNumber, type, ids, clientIds, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub statusReportAsync(ByVal userName As String, ByVal password As String, ByVal shortNumber As String, ByVal type As String, ByVal ids() As Long, ByVal clientIds() As String, ByVal userState As Object)
            If (Me.statusReportOperationCompleted Is Nothing) Then
                Me.statusReportOperationCompleted = AddressOf Me.OnstatusReportOperationCompleted
            End If
            Me.InvokeAsync("statusReport", New Object() {userName, password, shortNumber, type, ids, clientIds}, Me.statusReportOperationCompleted, userState)
        End Sub
        
        Private Sub OnstatusReportOperationCompleted(ByVal arg As Object)
            If (Not (Me.statusReportCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent statusReportCompleted(Me, New statusReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class MultiAddressMessageObject
        
        Private contentField As String
        
        Private encodingField As Short
        
        Private phoneNumbersField() As String
        
        Private clientIdsField() As String
        
        Private dueTimeField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property content() As String
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property encoding() As Short
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable:=false)>  _
        Public Property phoneNumbers() As String()
            Get
                Return Me.phoneNumbersField
            End Get
            Set
                Me.phoneNumbersField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable:=false)>  _
        Public Property clientIds() As String()
            Get
                Return Me.clientIdsField
            End Get
            Set
                Me.clientIdsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property dueTime() As Date
            Get
                Return Me.dueTimeField
            End Get
            Set
                Me.dueTimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class OutgoingMessage
        
        Private idField As Long
        
        Private clientIdField As String
        
        Private statusField As Short
        
        Private toField As String
        
        Private timeField As Date
        
        Private contentField As String
        
        '''<remarks/>
        Public Property id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property clientId() As String
            Get
                Return Me.clientIdField
            End Get
            Set
                Me.clientIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property status() As Short
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property [to]() As String
            Get
                Return Me.toField
            End Get
            Set
                Me.toField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property time() As Date
            Get
                Return Me.timeField
            End Get
            Set
                Me.timeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property content() As String
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class StatusReport
        
        Private idField As Long
        
        Private statusField As Short
        
        Private clientIdField As String
        
        '''<remarks/>
        Public Property id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property status() As Short
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property clientId() As String
            Get
                Return Me.clientIdField
            End Get
            Set
                Me.clientIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class MessageObject
        
        Private chunkField As Integer
        
        Private clientIdField As String
        
        Private contentField As String
        
        Private encodingField As Short
        
        Private idField As Long
        
        Private phoneNumberField As String
        
        Private statusField As Short
        
        Private timeField As System.Nullable(Of Date)
        
        '''<remarks/>
        Public Property chunk() As Integer
            Get
                Return Me.chunkField
            End Get
            Set
                Me.chunkField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property clientId() As String
            Get
                Return Me.clientIdField
            End Get
            Set
                Me.clientIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property content() As String
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property encoding() As Short
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property phoneNumber() As String
            Get
                Return Me.phoneNumberField
            End Get
            Set
                Me.phoneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property status() As Short
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property time() As System.Nullable(Of Date)
            Get
                Return Me.timeField
            End Get
            Set
                Me.timeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class IncomingMessage
        
        Private contentField As String
        
        Private encodingField As Short
        
        Private fromField As String
        
        Private idField As Long
        
        Private requestField As Object
        
        Private statusField As Short
        
        Private timeField As System.Nullable(Of Date)
        
        Private toField As String
        
        Private typeField As Short
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property content() As String
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property encoding() As Short
            Get
                Return Me.encodingField
            End Get
            Set
                Me.encodingField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property from() As String
            Get
                Return Me.fromField
            End Get
            Set
                Me.fromField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property id() As Long
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property request() As Object
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property status() As Short
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property time() As System.Nullable(Of Date)
            Get
                Return Me.timeField
            End Get
            Set
                Me.timeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property [to]() As String
            Get
                Return Me.toField
            End Get
            Set
                Me.toField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property type() As Short
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(ReportResult)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(StatusReportResult)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(ReceiveResult)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(BalanceResult)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(SendResult)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public MustInherit Class Result
        
        Private statusField As Short
        
        '''<remarks/>
        Public Property status() As Short
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class ReportResult
        Inherits Result
        
        Private messagesField() As OutgoingMessage
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("messages", IsNullable:=false)>  _
        Public Property messages() As OutgoingMessage()
            Get
                Return Me.messagesField
            End Get
            Set
                Me.messagesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class StatusReportResult
        Inherits Result
        
        Private reportField() As StatusReport
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("report", IsNullable:=false)>  _
        Public Property report() As StatusReport()
            Get
                Return Me.reportField
            End Get
            Set
                Me.reportField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class ReceiveResult
        Inherits Result
        
        Private messagesField() As IncomingMessage
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("messages", IsNullable:=false)>  _
        Public Property messages() As IncomingMessage()
            Get
                Return Me.messagesField
            End Get
            Set
                Me.messagesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class BalanceResult
        Inherits Result
        
        Private balanceField As Long
        
        '''<remarks/>
        Public Property balance() As Long
            Get
                Return Me.balanceField
            End Get
            Set
                Me.balanceField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.adpdigital.com/services/messaging")>  _
    Partial Public Class SendResult
        Inherits Result
        
        Private idField() As Long
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true),  _
         System.Xml.Serialization.XmlArrayItemAttribute("id", IsNullable:=false)>  _
        Public Property id() As Long()
            Get
                Return Me.idField
            End Get
            Set
                Me.idField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub sendMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As sendMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class sendMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SendResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SendResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub getBalanceCompletedEventHandler(ByVal sender As Object, ByVal e As getBalanceCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getBalanceCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BalanceResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BalanceResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub changePasswordCompletedEventHandler(ByVal sender As Object, ByVal e As changePasswordCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class changePasswordCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Short
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Short)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub getStatusCompletedEventHandler(ByVal sender As Object, ByVal e As getStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Short
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Short)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub receiveCompletedEventHandler(ByVal sender As Object, ByVal e As receiveCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class receiveCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ReceiveResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ReceiveResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub sendCompletedEventHandler(ByVal sender As Object, ByVal e As sendCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class sendCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SendResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SendResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub reportCompletedEventHandler(ByVal sender As Object, ByVal e As reportCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class reportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ReportResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ReportResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub statusReportCompletedEventHandler(ByVal sender As Object, ByVal e As statusReportCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class statusReportCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As StatusReportResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),StatusReportResult)
            End Get
        End Property
    End Class
End Namespace
