'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18408
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
'
Namespace com.hafezpayam.messagingws
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SendSMSSoap", [Namespace]:="MessagingWS")>  _
    Partial Public Class SendSMS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetSystemCreditOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getDeliverystatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SingleSMSEngineOperationCompleted As System.Threading.SendOrPostCallback
        
        Private singleSMSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private MultiSMSEngineOperationCompleted As System.Threading.SendOrPostCallback
        
        Private readInboxOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SmsProvider.My.MySettings.Default.SmsProvider_com_hafezpayam_messagingws_SendSMS
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetSystemCreditCompleted As GetSystemCreditCompletedEventHandler
        
        '''<remarks/>
        Public Event getDeliverystatusCompleted As getDeliverystatusCompletedEventHandler
        
        '''<remarks/>
        Public Event SingleSMSEngineCompleted As SingleSMSEngineCompletedEventHandler
        
        '''<remarks/>
        Public Event singleSMSCompleted As singleSMSCompletedEventHandler
        
        '''<remarks/>
        Public Event MultiSMSEngineCompleted As MultiSMSEngineCompletedEventHandler
        
        '''<remarks/>
        Public Event readInboxCompleted As readInboxCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MessagingWS/GetSystemCredit", RequestNamespace:="MessagingWS", ResponseNamespace:="MessagingWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSystemCredit(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String) As Long
            Dim results() As Object = Me.Invoke("GetSystemCredit", New Object() {PortalCode, UserName, PassWord})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSystemCreditAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String)
            Me.GetSystemCreditAsync(PortalCode, UserName, PassWord, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSystemCreditAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal userState As Object)
            If (Me.GetSystemCreditOperationCompleted Is Nothing) Then
                Me.GetSystemCreditOperationCompleted = AddressOf Me.OnGetSystemCreditOperationCompleted
            End If
            Me.InvokeAsync("GetSystemCredit", New Object() {PortalCode, UserName, PassWord}, Me.GetSystemCreditOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSystemCreditOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSystemCreditCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSystemCreditCompleted(Me, New GetSystemCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MessagingWS/getDeliverystatus", RequestNamespace:="MessagingWS", ResponseNamespace:="MessagingWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getDeliverystatus(ByVal PortalCode As Integer, ByVal UserName As String, ByVal password As String, ByVal serverType As Integer, ByVal ids() As Long) As Integer()
            Dim results() As Object = Me.Invoke("getDeliverystatus", New Object() {PortalCode, UserName, password, serverType, ids})
            Return CType(results(0),Integer())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getDeliverystatusAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal password As String, ByVal serverType As Integer, ByVal ids() As Long)
            Me.getDeliverystatusAsync(PortalCode, UserName, password, serverType, ids, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getDeliverystatusAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal password As String, ByVal serverType As Integer, ByVal ids() As Long, ByVal userState As Object)
            If (Me.getDeliverystatusOperationCompleted Is Nothing) Then
                Me.getDeliverystatusOperationCompleted = AddressOf Me.OngetDeliverystatusOperationCompleted
            End If
            Me.InvokeAsync("getDeliverystatus", New Object() {PortalCode, UserName, password, serverType, ids}, Me.getDeliverystatusOperationCompleted, userState)
        End Sub
        
        Private Sub OngetDeliverystatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.getDeliverystatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getDeliverystatusCompleted(Me, New getDeliverystatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MessagingWS/SingleSMSEngine", RequestNamespace:="MessagingWS", ResponseNamespace:="MessagingWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SingleSMSEngine(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal Mobile As String, ByVal Message As String, ByVal FlashSMS As Boolean, ByVal ServerType As Integer) As Long
            Dim results() As Object = Me.Invoke("SingleSMSEngine", New Object() {PortalCode, UserName, PassWord, Mobile, Message, FlashSMS, ServerType})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SingleSMSEngineAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal Mobile As String, ByVal Message As String, ByVal FlashSMS As Boolean, ByVal ServerType As Integer)
            Me.SingleSMSEngineAsync(PortalCode, UserName, PassWord, Mobile, Message, FlashSMS, ServerType, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SingleSMSEngineAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal Mobile As String, ByVal Message As String, ByVal FlashSMS As Boolean, ByVal ServerType As Integer, ByVal userState As Object)
            If (Me.SingleSMSEngineOperationCompleted Is Nothing) Then
                Me.SingleSMSEngineOperationCompleted = AddressOf Me.OnSingleSMSEngineOperationCompleted
            End If
            Me.InvokeAsync("SingleSMSEngine", New Object() {PortalCode, UserName, PassWord, Mobile, Message, FlashSMS, ServerType}, Me.SingleSMSEngineOperationCompleted, userState)
        End Sub
        
        Private Sub OnSingleSMSEngineOperationCompleted(ByVal arg As Object)
            If (Not (Me.SingleSMSEngineCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SingleSMSEngineCompleted(Me, New SingleSMSEngineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MessagingWS/singleSMS", RequestNamespace:="MessagingWS", ResponseNamespace:="MessagingWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function singleSMS(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal Mobile As String, ByVal Message As String, ByVal ServerType As Integer) As Long
            Dim results() As Object = Me.Invoke("singleSMS", New Object() {PortalCode, UserName, PassWord, Mobile, Message, ServerType})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub singleSMSAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal Mobile As String, ByVal Message As String, ByVal ServerType As Integer)
            Me.singleSMSAsync(PortalCode, UserName, PassWord, Mobile, Message, ServerType, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub singleSMSAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal Mobile As String, ByVal Message As String, ByVal ServerType As Integer, ByVal userState As Object)
            If (Me.singleSMSOperationCompleted Is Nothing) Then
                Me.singleSMSOperationCompleted = AddressOf Me.OnsingleSMSOperationCompleted
            End If
            Me.InvokeAsync("singleSMS", New Object() {PortalCode, UserName, PassWord, Mobile, Message, ServerType}, Me.singleSMSOperationCompleted, userState)
        End Sub
        
        Private Sub OnsingleSMSOperationCompleted(ByVal arg As Object)
            If (Not (Me.singleSMSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent singleSMSCompleted(Me, New singleSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MessagingWS/MultiSMSEngine", RequestNamespace:="MessagingWS", ResponseNamespace:="MessagingWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function MultiSMSEngine(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal Mobiles() As String, ByVal Messages() As String, ByVal FlashSMS As Boolean, ByVal ServerType As Integer, ByRef retCode As Integer) As Long()
            Dim results() As Object = Me.Invoke("MultiSMSEngine", New Object() {PortalCode, UserName, PassWord, Mobiles, Messages, FlashSMS, ServerType, retCode})
            retCode = CType(results(1),Integer)
            Return CType(results(0),Long())
        End Function
        
        '''<remarks/>
        Public Overloads Sub MultiSMSEngineAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal Mobiles() As String, ByVal Messages() As String, ByVal FlashSMS As Boolean, ByVal ServerType As Integer, ByVal retCode As Integer)
            Me.MultiSMSEngineAsync(PortalCode, UserName, PassWord, Mobiles, Messages, FlashSMS, ServerType, retCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub MultiSMSEngineAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal Mobiles() As String, ByVal Messages() As String, ByVal FlashSMS As Boolean, ByVal ServerType As Integer, ByVal retCode As Integer, ByVal userState As Object)
            If (Me.MultiSMSEngineOperationCompleted Is Nothing) Then
                Me.MultiSMSEngineOperationCompleted = AddressOf Me.OnMultiSMSEngineOperationCompleted
            End If
            Me.InvokeAsync("MultiSMSEngine", New Object() {PortalCode, UserName, PassWord, Mobiles, Messages, FlashSMS, ServerType, retCode}, Me.MultiSMSEngineOperationCompleted, userState)
        End Sub
        
        Private Sub OnMultiSMSEngineOperationCompleted(ByVal arg As Object)
            If (Not (Me.MultiSMSEngineCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent MultiSMSEngineCompleted(Me, New MultiSMSEngineCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("MessagingWS/readInbox", RequestNamespace:="MessagingWS", ResponseNamespace:="MessagingWS", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function readInbox(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal latestCount As Integer, ByRef returnStatus As Integer) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("readInbox", New Object() {PortalCode, UserName, PassWord, latestCount, returnStatus})
            returnStatus = CType(results(1),Integer)
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub readInboxAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal latestCount As Integer, ByVal returnStatus As Integer)
            Me.readInboxAsync(PortalCode, UserName, PassWord, latestCount, returnStatus, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub readInboxAsync(ByVal PortalCode As Integer, ByVal UserName As String, ByVal PassWord As String, ByVal latestCount As Integer, ByVal returnStatus As Integer, ByVal userState As Object)
            If (Me.readInboxOperationCompleted Is Nothing) Then
                Me.readInboxOperationCompleted = AddressOf Me.OnreadInboxOperationCompleted
            End If
            Me.InvokeAsync("readInbox", New Object() {PortalCode, UserName, PassWord, latestCount, returnStatus}, Me.readInboxOperationCompleted, userState)
        End Sub
        
        Private Sub OnreadInboxOperationCompleted(ByVal arg As Object)
            If (Not (Me.readInboxCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent readInboxCompleted(Me, New readInboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub GetSystemCreditCompletedEventHandler(ByVal sender As Object, ByVal e As GetSystemCreditCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSystemCreditCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub getDeliverystatusCompletedEventHandler(ByVal sender As Object, ByVal e As getDeliverystatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getDeliverystatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub SingleSMSEngineCompletedEventHandler(ByVal sender As Object, ByVal e As SingleSMSEngineCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SingleSMSEngineCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub singleSMSCompletedEventHandler(ByVal sender As Object, ByVal e As singleSMSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class singleSMSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub MultiSMSEngineCompletedEventHandler(ByVal sender As Object, ByVal e As MultiSMSEngineCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class MultiSMSEngineCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property retCode() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")>  _
    Public Delegate Sub readInboxCompletedEventHandler(ByVal sender As Object, ByVal e As readInboxCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class readInboxCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property returnStatus() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Integer)
            End Get
        End Property
    End Class
End Namespace
