'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
'
Namespace ir.payamak_service
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BasicHttpBinding_ISendService", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SendService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendSMSOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetCreditOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetDeilveryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetMessagesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetInboxCountOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SendBatchSmsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetBatchDeliveryOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetSenderNumbersOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SmsProvider.My.MySettings.Default.SmsProvider_ir_payamak_service_SendService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendSMSCompleted As SendSMSCompletedEventHandler
        
        '''<remarks/>
        Public Event GetCreditCompleted As GetCreditCompletedEventHandler
        
        '''<remarks/>
        Public Event GetDeilveryCompleted As GetDeilveryCompletedEventHandler
        
        '''<remarks/>
        Public Event GetMessagesCompleted As GetMessagesCompletedEventHandler
        
        '''<remarks/>
        Public Event GetInboxCountCompleted As GetInboxCountCompletedEventHandler
        
        '''<remarks/>
        Public Event SendBatchSmsCompleted As SendBatchSmsCompletedEventHandler
        
        '''<remarks/>
        Public Event GetBatchDeliveryCompleted As GetBatchDeliveryCompletedEventHandler
        
        '''<remarks/>
        Public Event GetSenderNumbersCompleted As GetSenderNumbersCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISendService/SendSMS", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SendSMS(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal userName As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal fromNumber As String, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")> ByVal toNumbers() As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal messageContent As String, ByVal isFlash As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal isFlashSpecified As Boolean, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable:=false)> ByRef recId() As Long, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary", IsNullable:=true)> ByRef status() As Byte, ByRef SendSMSResult As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef SendSMSResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("SendSMS", New Object() {userName, password, fromNumber, toNumbers, messageContent, isFlash, isFlashSpecified, recId, status})
            recId = CType(results(0),Long())
            status = CType(results(1),Byte())
            SendSMSResult = CType(results(2),Integer)
            SendSMSResultSpecified = CType(results(3),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendSMSAsync(ByVal userName As String, ByVal password As String, ByVal fromNumber As String, ByVal toNumbers() As String, ByVal messageContent As String, ByVal isFlash As Boolean, ByVal isFlashSpecified As Boolean, ByVal recId() As Long, ByVal status() As Byte)
            Me.SendSMSAsync(userName, password, fromNumber, toNumbers, messageContent, isFlash, isFlashSpecified, recId, status, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendSMSAsync(ByVal userName As String, ByVal password As String, ByVal fromNumber As String, ByVal toNumbers() As String, ByVal messageContent As String, ByVal isFlash As Boolean, ByVal isFlashSpecified As Boolean, ByVal recId() As Long, ByVal status() As Byte, ByVal userState As Object)
            If (Me.SendSMSOperationCompleted Is Nothing) Then
                Me.SendSMSOperationCompleted = AddressOf Me.OnSendSMSOperationCompleted
            End If
            Me.InvokeAsync("SendSMS", New Object() {userName, password, fromNumber, toNumbers, messageContent, isFlash, isFlashSpecified, recId, status}, Me.SendSMSOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendSMSOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendSMSCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendSMSCompleted(Me, New SendSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISendService/GetCredit", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub GetCredit(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal userName As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByRef GetCreditResult As Decimal, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef GetCreditResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("GetCredit", New Object() {userName, password})
            GetCreditResult = CType(results(0),Decimal)
            GetCreditResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCreditAsync(ByVal userName As String, ByVal password As String)
            Me.GetCreditAsync(userName, password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCreditAsync(ByVal userName As String, ByVal password As String, ByVal userState As Object)
            If (Me.GetCreditOperationCompleted Is Nothing) Then
                Me.GetCreditOperationCompleted = AddressOf Me.OnGetCreditOperationCompleted
            End If
            Me.InvokeAsync("GetCredit", New Object() {userName, password}, Me.GetCreditOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCreditOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCreditCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCreditCompleted(Me, New GetCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISendService/GetDeilvery", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub GetDeilvery(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal userName As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByVal recId As Long, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal recIdSpecified As Boolean, ByRef GetDeilveryResult As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef GetDeilveryResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("GetDeilvery", New Object() {userName, password, recId, recIdSpecified})
            GetDeilveryResult = CType(results(0),Integer)
            GetDeilveryResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDeilveryAsync(ByVal userName As String, ByVal password As String, ByVal recId As Long, ByVal recIdSpecified As Boolean)
            Me.GetDeilveryAsync(userName, password, recId, recIdSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetDeilveryAsync(ByVal userName As String, ByVal password As String, ByVal recId As Long, ByVal recIdSpecified As Boolean, ByVal userState As Object)
            If (Me.GetDeilveryOperationCompleted Is Nothing) Then
                Me.GetDeilveryOperationCompleted = AddressOf Me.OnGetDeilveryOperationCompleted
            End If
            Me.InvokeAsync("GetDeilvery", New Object() {userName, password, recId, recIdSpecified}, Me.GetDeilveryOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetDeilveryOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetDeilveryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetDeilveryCompleted(Me, New GetDeilveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISendService/GetMessages", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetMessages(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal userName As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByVal messageType As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal messageTypeSpecified As Boolean, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")> ByVal fromNumbers() As String, ByVal index As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal indexSpecified As Boolean, ByVal count As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal countSpecified As Boolean) As <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Models")> MessageInfo()
            Dim results() As Object = Me.Invoke("GetMessages", New Object() {userName, password, messageType, messageTypeSpecified, fromNumbers, index, indexSpecified, count, countSpecified})
            Return CType(results(0),MessageInfo())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetMessagesAsync(ByVal userName As String, ByVal password As String, ByVal messageType As Integer, ByVal messageTypeSpecified As Boolean, ByVal fromNumbers() As String, ByVal index As Integer, ByVal indexSpecified As Boolean, ByVal count As Integer, ByVal countSpecified As Boolean)
            Me.GetMessagesAsync(userName, password, messageType, messageTypeSpecified, fromNumbers, index, indexSpecified, count, countSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetMessagesAsync(ByVal userName As String, ByVal password As String, ByVal messageType As Integer, ByVal messageTypeSpecified As Boolean, ByVal fromNumbers() As String, ByVal index As Integer, ByVal indexSpecified As Boolean, ByVal count As Integer, ByVal countSpecified As Boolean, ByVal userState As Object)
            If (Me.GetMessagesOperationCompleted Is Nothing) Then
                Me.GetMessagesOperationCompleted = AddressOf Me.OnGetMessagesOperationCompleted
            End If
            Me.InvokeAsync("GetMessages", New Object() {userName, password, messageType, messageTypeSpecified, fromNumbers, index, indexSpecified, count, countSpecified}, Me.GetMessagesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetMessagesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetMessagesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetMessagesCompleted(Me, New GetMessagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISendService/GetInboxCount", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub GetInboxCount(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal userName As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByVal isRead As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal isReadSpecified As Boolean, ByRef GetInboxCountResult As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef GetInboxCountResultSpecified As Boolean)
            Dim results() As Object = Me.Invoke("GetInboxCount", New Object() {userName, password, isRead, isReadSpecified})
            GetInboxCountResult = CType(results(0),Integer)
            GetInboxCountResultSpecified = CType(results(1),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInboxCountAsync(ByVal userName As String, ByVal password As String, ByVal isRead As Boolean, ByVal isReadSpecified As Boolean)
            Me.GetInboxCountAsync(userName, password, isRead, isReadSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetInboxCountAsync(ByVal userName As String, ByVal password As String, ByVal isRead As Boolean, ByVal isReadSpecified As Boolean, ByVal userState As Object)
            If (Me.GetInboxCountOperationCompleted Is Nothing) Then
                Me.GetInboxCountOperationCompleted = AddressOf Me.OnGetInboxCountOperationCompleted
            End If
            Me.InvokeAsync("GetInboxCount", New Object() {userName, password, isRead, isReadSpecified}, Me.GetInboxCountOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetInboxCountOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetInboxCountCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetInboxCountCompleted(Me, New GetInboxCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISendService/SendBatchSms", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub SendBatchSms(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal userName As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal fromNumber As String, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")> ByVal toNumbers() As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal messageContent As String, ByVal isFlash As Boolean, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal isFlashSpecified As Boolean, ByRef SendBatchSmsResult As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef SendBatchSmsResultSpecified As Boolean, ByRef batchSmsId As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef batchSmsIdSpecified As Boolean)
            Dim results() As Object = Me.Invoke("SendBatchSms", New Object() {userName, password, fromNumber, toNumbers, messageContent, isFlash, isFlashSpecified})
            SendBatchSmsResult = CType(results(0),Integer)
            SendBatchSmsResultSpecified = CType(results(1),Boolean)
            batchSmsId = CType(results(2),Integer)
            batchSmsIdSpecified = CType(results(3),Boolean)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendBatchSmsAsync(ByVal userName As String, ByVal password As String, ByVal fromNumber As String, ByVal toNumbers() As String, ByVal messageContent As String, ByVal isFlash As Boolean, ByVal isFlashSpecified As Boolean)
            Me.SendBatchSmsAsync(userName, password, fromNumber, toNumbers, messageContent, isFlash, isFlashSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendBatchSmsAsync(ByVal userName As String, ByVal password As String, ByVal fromNumber As String, ByVal toNumbers() As String, ByVal messageContent As String, ByVal isFlash As Boolean, ByVal isFlashSpecified As Boolean, ByVal userState As Object)
            If (Me.SendBatchSmsOperationCompleted Is Nothing) Then
                Me.SendBatchSmsOperationCompleted = AddressOf Me.OnSendBatchSmsOperationCompleted
            End If
            Me.InvokeAsync("SendBatchSms", New Object() {userName, password, fromNumber, toNumbers, messageContent, isFlash, isFlashSpecified}, Me.SendBatchSmsOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendBatchSmsOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendBatchSmsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendBatchSmsCompleted(Me, New SendBatchSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISendService/GetBatchDelivery", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub GetBatchDelivery(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal userName As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String, ByVal batchSmsId As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal batchSmsIdSpecified As Boolean, ByVal index As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal indexSpecified As Boolean, ByVal count As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByVal countSpecified As Boolean, ByRef GetBatchDeliveryResult As Integer, <System.Xml.Serialization.XmlIgnoreAttribute()> ByRef GetBatchDeliveryResultSpecified As Boolean, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays")> ByRef numbers() As String, <System.Xml.Serialization.XmlArrayAttribute(IsNullable:=true), System.Xml.Serialization.XmlArrayItemAttribute([Namespace]:="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable:=false)> ByRef deliveryStatus() As Integer)
            Dim results() As Object = Me.Invoke("GetBatchDelivery", New Object() {userName, password, batchSmsId, batchSmsIdSpecified, index, indexSpecified, count, countSpecified})
            GetBatchDeliveryResult = CType(results(0),Integer)
            GetBatchDeliveryResultSpecified = CType(results(1),Boolean)
            numbers = CType(results(2),String())
            deliveryStatus = CType(results(3),Integer())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetBatchDeliveryAsync(ByVal userName As String, ByVal password As String, ByVal batchSmsId As Integer, ByVal batchSmsIdSpecified As Boolean, ByVal index As Integer, ByVal indexSpecified As Boolean, ByVal count As Integer, ByVal countSpecified As Boolean)
            Me.GetBatchDeliveryAsync(userName, password, batchSmsId, batchSmsIdSpecified, index, indexSpecified, count, countSpecified, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetBatchDeliveryAsync(ByVal userName As String, ByVal password As String, ByVal batchSmsId As Integer, ByVal batchSmsIdSpecified As Boolean, ByVal index As Integer, ByVal indexSpecified As Boolean, ByVal count As Integer, ByVal countSpecified As Boolean, ByVal userState As Object)
            If (Me.GetBatchDeliveryOperationCompleted Is Nothing) Then
                Me.GetBatchDeliveryOperationCompleted = AddressOf Me.OnGetBatchDeliveryOperationCompleted
            End If
            Me.InvokeAsync("GetBatchDelivery", New Object() {userName, password, batchSmsId, batchSmsIdSpecified, index, indexSpecified, count, countSpecified}, Me.GetBatchDeliveryOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetBatchDeliveryOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetBatchDeliveryCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetBatchDeliveryCompleted(Me, New GetBatchDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISendService/GetSenderNumbers", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetSenderNumbers(<System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal userName As String, <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> ByVal password As String) As <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)> String
            Dim results() As Object = Me.Invoke("GetSenderNumbers", New Object() {userName, password})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetSenderNumbersAsync(ByVal userName As String, ByVal password As String)
            Me.GetSenderNumbersAsync(userName, password, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetSenderNumbersAsync(ByVal userName As String, ByVal password As String, ByVal userState As Object)
            If (Me.GetSenderNumbersOperationCompleted Is Nothing) Then
                Me.GetSenderNumbersOperationCompleted = AddressOf Me.OnGetSenderNumbersOperationCompleted
            End If
            Me.InvokeAsync("GetSenderNumbers", New Object() {userName, password}, Me.GetSenderNumbersOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetSenderNumbersOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSenderNumbersCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSenderNumbersCompleted(Me, New GetSenderNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Models")>  _
    Partial Public Class MessageInfo
        
        Private actionDateTimeField As Date
        
        Private actionDateTimeFieldSpecified As Boolean
        
        Private contentField As String
        
        Private countField As Integer
        
        Private countFieldSpecified As Boolean
        
        Private descField As String
        
        Private flashField As Boolean
        
        Private flashFieldSpecified As Boolean
        
        Private isReadField As Boolean
        
        Private isReadFieldSpecified As Boolean
        
        Private langField As SMSLang
        
        Private langFieldSpecified As Boolean
        
        Private messageIdField As Integer
        
        Private messageIdFieldSpecified As Boolean
        
        Private messageTypeField As SMSDirectionType
        
        Private messageTypeFieldSpecified As Boolean
        
        Private moneyIsRefundedField As Boolean
        
        Private moneyIsRefundedFieldSpecified As Boolean
        
        Private notSentField As Integer
        
        Private notSentFieldSpecified As Boolean
        
        Private pagesField As Integer
        
        Private pagesFieldSpecified As Boolean
        
        Private receiverField As String
        
        Private senderField As String
        
        Private sentField As Integer
        
        Private sentFieldSpecified As Boolean
        
        Private statusField As SMSStatus
        
        Private statusFieldSpecified As Boolean
        
        Private tariffField As Decimal
        
        Private tariffFieldSpecified As Boolean
        
        Private titleField As String
        
        Private userIdField As Integer
        
        Private userIdFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property ActionDateTime() As Date
            Get
                Return Me.actionDateTimeField
            End Get
            Set
                Me.actionDateTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ActionDateTimeSpecified() As Boolean
            Get
                Return Me.actionDateTimeFieldSpecified
            End Get
            Set
                Me.actionDateTimeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Content() As String
            Get
                Return Me.contentField
            End Get
            Set
                Me.contentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Count() As Integer
            Get
                Return Me.countField
            End Get
            Set
                Me.countField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property CountSpecified() As Boolean
            Get
                Return Me.countFieldSpecified
            End Get
            Set
                Me.countFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Desc() As String
            Get
                Return Me.descField
            End Get
            Set
                Me.descField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Flash() As Boolean
            Get
                Return Me.flashField
            End Get
            Set
                Me.flashField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property FlashSpecified() As Boolean
            Get
                Return Me.flashFieldSpecified
            End Get
            Set
                Me.flashFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsRead() As Boolean
            Get
                Return Me.isReadField
            End Get
            Set
                Me.isReadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property IsReadSpecified() As Boolean
            Get
                Return Me.isReadFieldSpecified
            End Get
            Set
                Me.isReadFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Lang() As SMSLang
            Get
                Return Me.langField
            End Get
            Set
                Me.langField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LangSpecified() As Boolean
            Get
                Return Me.langFieldSpecified
            End Get
            Set
                Me.langFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MessageId() As Integer
            Get
                Return Me.messageIdField
            End Get
            Set
                Me.messageIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MessageIdSpecified() As Boolean
            Get
                Return Me.messageIdFieldSpecified
            End Get
            Set
                Me.messageIdFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MessageType() As SMSDirectionType
            Get
                Return Me.messageTypeField
            End Get
            Set
                Me.messageTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MessageTypeSpecified() As Boolean
            Get
                Return Me.messageTypeFieldSpecified
            End Get
            Set
                Me.messageTypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MoneyIsRefunded() As Boolean
            Get
                Return Me.moneyIsRefundedField
            End Get
            Set
                Me.moneyIsRefundedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property MoneyIsRefundedSpecified() As Boolean
            Get
                Return Me.moneyIsRefundedFieldSpecified
            End Get
            Set
                Me.moneyIsRefundedFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NotSent() As Integer
            Get
                Return Me.notSentField
            End Get
            Set
                Me.notSentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NotSentSpecified() As Boolean
            Get
                Return Me.notSentFieldSpecified
            End Get
            Set
                Me.notSentFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pages() As Integer
            Get
                Return Me.pagesField
            End Get
            Set
                Me.pagesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property PagesSpecified() As Boolean
            Get
                Return Me.pagesFieldSpecified
            End Get
            Set
                Me.pagesFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Receiver() As String
            Get
                Return Me.receiverField
            End Get
            Set
                Me.receiverField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Sender() As String
            Get
                Return Me.senderField
            End Get
            Set
                Me.senderField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sent() As Integer
            Get
                Return Me.sentField
            End Get
            Set
                Me.sentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property SentSpecified() As Boolean
            Get
                Return Me.sentFieldSpecified
            End Get
            Set
                Me.sentFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As SMSStatus
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StatusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tariff() As Decimal
            Get
                Return Me.tariffField
            End Get
            Set
                Me.tariffField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property TariffSpecified() As Boolean
            Get
                Return Me.tariffFieldSpecified
            End Get
            Set
                Me.tariffFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property Title() As String
            Get
                Return Me.titleField
            End Get
            Set
                Me.titleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserId() As Integer
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property UserIdSpecified() As Boolean
            Get
                Return Me.userIdFieldSpecified
            End Get
            Set
                Me.userIdFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/SMSPanel.Common.Enums")>  _
    Public Enum SMSLang
        
        '''<remarks/>
        None
        
        '''<remarks/>
        FA
        
        '''<remarks/>
        EN
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Enums")>  _
    Public Enum SMSDirectionType
        
        '''<remarks/>
        None
        
        '''<remarks/>
        [In]
        
        '''<remarks/>
        Out
        
        '''<remarks/>
        Schedule
        
        '''<remarks/>
        Usance
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34281"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://schemas.datacontract.org/2004/07/SMSPanel.Domain.Enums")>  _
    Public Enum SMSStatus
        
        '''<remarks/>
        None
        
        '''<remarks/>
        Pending
        
        '''<remarks/>
        Illegal
        
        '''<remarks/>
        Sending
        
        '''<remarks/>
        NotApproved
        
        '''<remarks/>
        Sent
        
        '''<remarks/>
        Canceled
        
        '''<remarks/>
        [Error]
        
        '''<remarks/>
        NoCredit
        
        '''<remarks/>
        NotSent
        
        '''<remarks/>
        WaitForSend
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SendSMSCompletedEventHandler(ByVal sender As Object, ByVal e As SendSMSCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendSMSCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property recId() As Long()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property status() As Byte()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Byte())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property SendSMSResult() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property SendSMSResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetCreditCompletedEventHandler(ByVal sender As Object, ByVal e As GetCreditCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCreditCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property GetCreditResult() As Decimal
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Decimal)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property GetCreditResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetDeilveryCompletedEventHandler(ByVal sender As Object, ByVal e As GetDeilveryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetDeilveryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property GetDeilveryResult() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property GetDeilveryResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetMessagesCompletedEventHandler(ByVal sender As Object, ByVal e As GetMessagesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetMessagesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As MessageInfo()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),MessageInfo())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetInboxCountCompletedEventHandler(ByVal sender As Object, ByVal e As GetInboxCountCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetInboxCountCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property GetInboxCountResult() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property GetInboxCountResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub SendBatchSmsCompletedEventHandler(ByVal sender As Object, ByVal e As SendBatchSmsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendBatchSmsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property SendBatchSmsResult() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property SendBatchSmsResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property batchSmsId() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property batchSmsIdSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetBatchDeliveryCompletedEventHandler(ByVal sender As Object, ByVal e As GetBatchDeliveryCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetBatchDeliveryCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property GetBatchDeliveryResult() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property GetBatchDeliveryResultSpecified() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),Boolean)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property numbers() As String()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(2),String())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property deliveryStatus() As Integer()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(3),Integer())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")>  _
    Public Delegate Sub GetSenderNumbersCompletedEventHandler(ByVal sender As Object, ByVal e As GetSenderNumbersCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetSenderNumbersCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
